spring:
  application:
    name: web-shop-project
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show-sql: true
        format_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.MySQL8Dialect

  data:
    redis:
      host: localhost
      port: 6379

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}   # 환경 변수 사용
    password: ${MAIL_PASSWORD}   # 환경 변수 사용
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.starttls.required: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

file:
  upload-dir: src/main/resources/static/images

payment:
  toss:
    test_client_api_key : test_ck_yL0qZ4G1VOKEYlzReJawVoWb2MQY
    test_secret_api_key : test_sk_ex6BJGQOVDpJN6kDPQeaVW4w2zNb